version: '3'
services:
    hexo:
      image: alpine
      container_name: pusher
      working_dir: /root
      volumes:
        - "./public:/root/public"
        - "./blog:/root/blog"
        - "./entrypoint.sh:/entrypoint.sh"
      stdin_open: true
      tty:  true
      environment:
        - SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY
        - TARGET_REPO=$TARGET_REPO
      entrypoint: /entrypoint.sh