name: Generate website

on: 
  push:
  delete:
  create:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - name: update submodule
        run: |
          git config --global pull.rebase true
          cd themes/butterfly && git checkout master && git pull
          cd ../../
          cd source/source && git pull
      # - name: Setup Debug Session
      #   uses: mxschmitt/action-tmate@v3
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      #     SOURCE_REPO: git@github.com:A-JiuA/blog.git
      #   timeout-minutes: 15
      #   with:
      #     detached:  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Setup Node.js
        uses: actions/setup-node@v3  #安装node.js
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          pip3 install requests wget
      - name: Update
        run: |
          npm install -g hexo-cli npm-check
          npm install --save
          npm-check -u
          npm update -g
          npm update --save
      - name: Get Articles
        env:
          API: ${{ secrets.API }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python3 getArticles.py
      - name: Clone Repository
        run: git clone --depth=3 https://github.com/A-JiuA/blog.git blog
      - name: Generate
        run: |
          hexo cl
          hexo g
      - name: Push to Github
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
          TARGET_REPO: git@github.com:A-JiuA/blog.git
        run: |
          chmod +x entrypoint.sh
          docker-compose up && docker rm pusher
      - name: Generate(Gitee)
        run: |
          cp configs/_config.gitee.yml _config.yml
          hexo cl
          hexo g
      - name: Push to Gitee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
          TARGET_REPO: git@gitee.com:A-JiuA/blog.git
        run: |
          chmod +x entrypoint.sh
          docker-compose up && docker rm pusher
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: A-JiuA
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: A-JiuA/blog
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: main
      - name: reset config
        run: |
          cp configs/_config.github.yml _config.yml
          rm -rf blog
          hexo cl
      - name: Commit
        run: |
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          if [[ -n $(git status --porcelain) ]]
          then
            git add .
            git commit -m 'update modules'
            git push || true
          else
            echo "Nothing to commit."
          fi
