name: Generate website

on: 
  push:
  delete:
  create:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Node.js
        uses: actions/setup-node  #安装node.js
        with:
          node-version: '18'
      - name: Update
        run: |
          npm install -g hexo-cli npm-check npm-upgrade
          npm install --save
          npm-check
          npm-upgrade
          npm update -g
          npm update --save
      - name: set private key
        run: |
          echo ${ secrets.GITEE_PRIVATE_KEY } > ~/.ssh/id_rsa
      - name: Generate
        run: |
          hexo cl
          hexo g
      - name: Push to Github
        run: |
          hexo d
      - name: Generate(Gitee)
        run: |
          sed "s/git@github.com/git@gitee.com/g" _config.yml
          sed "s/A-JiuA.github.io/A-JiuA.gitee.io/g" _config.yml
          hexo g
      - name: Push to Gitee
        run: |
          hexo d
    #   - name: Sync to Gitee
    #     uses: wearerequired/git-mirror-action@master
    #     env:
    #       SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
    #     with:
    #       source-repo: git@github.com:A-JiuA/blog.git
    #       destination-repo: git@gitee.com:A-JiuA/blog.git
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: A-JiuA
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: A-JiuA/blog
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: main
      - name: reset config
        run: |
          sed "s/git@gitee.com/git@github.com/g" _config.yml
          sed "s/A-JiuA.gitee.io/A-JiuA.github.io/g" _config.yml
          hexo cl
      - name: Commit
        run: |
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add DLLs
          git commit -m "update modules"
          git pull

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
